/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucms.gui.authentication;

import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import ucms.Admin;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
/**
 *
 * @author USER
 */
public class ViewFeedbackUI extends javax.swing.JFrame {

    /**
     * Creates new form ApproveDriverForm
     */
    private static Admin currentAdmin;
    private final int noCollIndex =2;
    private final int noColWidth = 75;
    public ViewFeedbackUI(Admin currAdmin) {
        initComponents();
        
        this.currentAdmin = currAdmin;
        welcomeAdminHeader.setText("Welcome " + currentAdmin.getAdminName());
        setColumnWidth();
        loadFeedback();
        
    }
    
    private void setColumnWidth(){
        TableColumnModel colModel = FeedbackTable.getColumnModel();
        colModel.getColumn(noCollIndex).setPreferredWidth(noColWidth);
        colModel.getColumn(noCollIndex).setMaxWidth(noColWidth);
        colModel.getColumn(noCollIndex).setMinWidth(noColWidth);
    }

    private void loadFeedback() {
        DefaultTableModel model = (DefaultTableModel) FeedbackTable.getModel();
        model.setRowCount(0);
        try {
            Connection conn = ucms.database.DBConnection.getConnection();
            String sql = "SELECT f.feedback_id, f.comment, "
                    + "sd.student_name AS driver_name, "
                    + "sp.student_name AS passenger_name "
                    + "FROM feedback f "
                    + "JOIN driver d ON f.driver_id = d.driver_id "
                    + "JOIN student sd ON d.student_id = sd.student_id "
                    + "JOIN student sp ON f.student_id = sp.student_id";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("feedback_id"),
                    rs.getString("comment"),
                    rs.getString("driver_name"),
                    rs.getString("passenger_name")
                });
            }
            rs.close();
            ps.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error loading feedback: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        approveDriver = new javax.swing.JPanel();
        welcomeAdminHeader = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        FeedbackTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Logout1 = new javax.swing.JButton();
        ViewFeedback1 = new javax.swing.JButton();
        ApproveDriver4 = new javax.swing.JButton();
        ViewFeedback2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        approveDriver.setBackground(new java.awt.Color(30, 30, 30));

        welcomeAdminHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeAdminHeader.setForeground(new java.awt.Color(255, 255, 255));
        welcomeAdminHeader.setText("View Feedback");

        javax.swing.GroupLayout approveDriverLayout = new javax.swing.GroupLayout(approveDriver);
        approveDriver.setLayout(approveDriverLayout);
        approveDriverLayout.setHorizontalGroup(
            approveDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(approveDriverLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(welcomeAdminHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        approveDriverLayout.setVerticalGroup(
            approveDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(approveDriverLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(welcomeAdminHeader)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(30, 30, 30));

        back.setText("Back");
        back.setToolTipText("");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Display Feedback from passengers");

        FeedbackTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Feedback ID", "Comment", "Driver Name", "Passanger Name"
            }
        ));
        FeedbackTable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                FeedbackTableMouseMoved(evt);
            }
        });
        FeedbackTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FeedbackTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(FeedbackTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(name))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(name)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(15, 61, 92));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 180, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ucms/resources/t-UMPang_logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        jPanel6.setBackground(new java.awt.Color(15, 61, 92));

        Logout1.setBackground(new java.awt.Color(15, 61, 92));
        Logout1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Logout1.setForeground(new java.awt.Color(255, 51, 51));
        Logout1.setText("LOGOUT");
        Logout1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout1ActionPerformed(evt);
            }
        });

        ViewFeedback1.setBackground(new java.awt.Color(51, 255, 51));
        ViewFeedback1.setText("View Report");
        ViewFeedback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewFeedback1ActionPerformed(evt);
            }
        });

        ApproveDriver4.setBackground(new java.awt.Color(255, 153, 0));
        ApproveDriver4.setText("Approve Driver");
        ApproveDriver4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveDriver4ActionPerformed(evt);
            }
        });

        ViewFeedback2.setBackground(new java.awt.Color(255, 255, 0));
        ViewFeedback2.setText("View Feedback");
        ViewFeedback2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewFeedback2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Logout1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(ViewFeedback1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApproveDriver4)
                    .addComponent(ViewFeedback2))
                .addGap(24, 24, 24))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(ViewFeedback1)
                .addGap(18, 18, 18)
                .addComponent(ViewFeedback2)
                .addGap(18, 18, 18)
                .addComponent(ApproveDriver4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(Logout1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(approveDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(approveDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new AdminDashboardUI(currentAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void FeedbackTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbackTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FeedbackTableMouseClicked

    private void FeedbackTableMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbackTableMouseMoved
        // TODO add your handling code here:
        int row = FeedbackTable.rowAtPoint(evt.getPoint());
        int col = FeedbackTable.columnAtPoint(evt.getPoint());
        if (row >= 0 && col == 1) { 
            Object val = FeedbackTable.getValueAt(row, col);
            FeedbackTable.setToolTipText(val == null ? null : val.toString());
        }
    }//GEN-LAST:event_FeedbackTableMouseMoved

    private void Logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout1ActionPerformed
        new LoginAdminUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Logout1ActionPerformed

    private void ViewFeedback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewFeedback1ActionPerformed
        // TODO add your handling code here:
        new ViewReportUI(currentAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewFeedback1ActionPerformed

    private void ApproveDriver4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveDriver4ActionPerformed
        // TODO add your handling code here:
        new ApproveDriverUI(currentAdmin).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_ApproveDriver4ActionPerformed

    private void ViewFeedback2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewFeedback2ActionPerformed
        // TODO add your handling code here:
        new ViewFeedbackUI(currentAdmin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewFeedback2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFeedbackUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFeedbackUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFeedbackUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFeedbackUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFeedbackUI(currentAdmin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApproveDriver4;
    private javax.swing.JTable FeedbackTable;
    private javax.swing.JButton Logout1;
    private javax.swing.JButton ViewFeedback1;
    private javax.swing.JButton ViewFeedback2;
    private javax.swing.JPanel approveDriver;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel name;
    private javax.swing.JLabel welcomeAdminHeader;
    // End of variables declaration//GEN-END:variables
}
